name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - dgooch5200
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Well Com or Flarecon
      description: What version of our software are you running?
      options:
        - Well Com
        - Flarecon
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What Phone/Tablet are you seeing the problem on?
      multiple: true
      options:
        - Apple
        - Android
        - Other
  - type: textarea
    id: Model
    attributes:
      label:  Phone/Tablet Model
      description: What is the Phone/Tablet model name you are using? 
      render: shell
    
  - type: textarea
    id: Version
    attributes:
      label:  Phone/Tablet software version
      description: What is the Phone/Tablet software version? 
      render: shell
  
  
