name: 🚀 New feature proposal
description: Propose a new feature
title: "[Enhancement]"
labels: ["Enhancement"]
assignees:
  - dgooch5200
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Well Com
        - Flarecon
    validations:
     required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: 'A clear and concise description of what you want to happen.'
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: "Clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  
